apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-storage-openebs-hostpath-pvc
  namespace: arc-systems
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath
