name: 'gcloud_auth'
description: 'GCP authentication'
inputs:
  repository_name:
    description: 'Repository name'
    required: true
  region:
    description: 'Geographical region to be used for the GCP artifact registry'
    required: true
  ci_service_account:
    description: 'Base64 encoded service account to be used inside the CI'
    required: true
  google_application_credentials:
    description: 'Local path of the service account that will be stored'
    default: keys/service_account.json
runs:
  using: "composite"
  steps:
    - run: mkdir -p $(dirname ${{ inputs.google_application_credentials }}) && echo ${{ inputs.ci_service_account }} | base64 -d > ${{ inputs.google_application_credentials }}
      shell: bash
      working-directory: ${{ inputs.repository_name }}
    - run: gcloud auth activate-service-account --key-file=${{ inputs.google_application_credentials }}
      shell: bash
      working-directory: ${{ inputs.repository_name }}
    - run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev
      shell: bash
