name: 'gcloud_auth'
description: 'GCP authentication'
inputs:
  credentials_json:
    description: 'Base64 encoded service account to be used inside the CI'
    required: true
runs:
  using: "composite"
  steps:
    - id: gcloud_auth
      name: GCP authentication
      uses: google-github-actions/auth@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        credentials_json: ${{ inputs.credentials_json }}
    - run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
      shell: bash
