name: 'initialize_terraform'
description: ''
inputs:
  workspace:
    description: 'Terraform workspace to use, can be either "base" or "$REPOSITORY_NAME"'
    required: false
    default: ""

runs:
  using: "composite"
  steps:

    - uses: ./.github/actions/set_up_terraform

    - run: |
        if [[ ${{ inputs.workspace }} != "base" && ${{ inputs.workspace }} != "$REPOSITORY_NAME" ]]; then
          echo "Incorrect workspace input: expected $REPOSITORY_NAME or base, got ${{ inputs.workspace }}"
          exit 1
        fi
      shell: bash

    - run: |
          cd ${{ env.REPOSITORY_NAME }}/iac
          
          # run terraform init and create the terraform state locally
          terraform init -input=false -backend-config="bucket=$STATE_BUCKET"
          
          # if empty inputs.workspace
          if [ -z ${{ inputs.workspace }} ]; then
            workspace=${{ env.REPOSITORY_NAME }}
          else
            workspace=${{ inputs.workspace }}
          fi
          
          terraform workspace select $workspace || terraform workspace new $workspace
      shell: bash

    - id: release_terraform_lock
      if: ${{ failure() && steps.terraform_with_retry.conclusion == 'failure' }}
      run: gcloud storage rm gs://$STATE_BUCKET/terraform/state/${{ inputs.workspace }}.tflock || true
      shell: bash
