repository_variables:
  - MAIN_TERRAFORM_RESOURCES=module.${MAIN_TERRAFORM_MODULE_NAME}
  # monorepo
  - MONO_REPOSITORY_NAME=neuronest
  # must be overriden in subsequent repositories, if exists
  # PACKAGE_NAME=
  # MAIN_TERRAFORM_MODULE_NAME=
multi_instance_resource_names: []
  # must be overriden in subsequent repositories, if exists
  # BASE_IMAGE_NAME=
other_variables:
  branch:
    default:
      # GCP general
      - ORGANIZATION_ID=385885390984
      - BILLING_ACCOUNT=01F17D-FFD0ED-C23C3B
      - DEFAULT_PROJECTS_OWNERS=come.arvis@neuronest.net,guillaume.ligner@neuronest.net
      # GCP projects
      - PROJECT_ID=dummy-project-id
      - PROJECT_CODE=dpi
      - FUNCTIONAL_SERVICES_PROJECT_ID=functional-services
      - NON_FUNCTIONAL_SERVICES_PROJECT_ID=non-functional-services
      - FUNCTIONAL_SERVICES_PROJECT_CODE=fs
      - NON_FUNCTIONAL_SERVICES_PROJECT_CODE=nfs
      - REGION=europe-west1
      - ZONE=europe-west1-b
      - TIMEZONE=Europe/Paris
      - PROJECT_BUILDER_SERVICE_ACCOUNT_NAME=project-owner
      - PROJECT_BUILDER_SERVICE_ACCOUNT_EMAIL=${PROJECT_BUILDER_SERVICE_ACCOUNT_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
      # region specific to firestore
      # (see https://cloud.google.com/appengine/docs/standard/locations#cloud-firestore-location)
      - FIRESTORE_REGION=europe-west3
      # poetry
      - POETRY_VERSION=1.7.1
      # docker hub
      - DOCKER_REPOSITORY_NAME=neuronest
      # terraform
      - BASE_TERRAFORM_RESOURCES=module.base
      - STATE_BUCKET=${PROJECT_CODE}-tfstate
      # artifact registry
      - GCP_REGISTRY_NAME=${REGION}-docker.pkg.dev/${PROJECT_ID}
