api:
  maximum_videos_number: 10

job:
  container_uri: '${oc.env:IMAGE_NAME}'
  cpu: '1.0'
  memory: '4Gi'

preprocessing:
  image_width: 400

postprocessing:
  class_name: "person"
  confidence_threshold: 0.15

paths:
  videos_directory: "data"
  outputs_directory: "outputs"
  labels: "${paths.videos_directory}/labels.csv"
  benchmark: "${paths.outputs_directory}/benchmark.csv"
  scores: "${paths.outputs_directory}/scores.csv"
  output_file_suffix: "_results.txt"
  output_video_suffix: "_results.avi"

algorithm:
  line_placement_ratio: 0.5
  inference_periodicity: 15
  centroid_tracker:
    max_disappeared: 5
    max_distance_height_ratio: 0.2

model:
  confidence_threshold: 0.15
