name: 'run_linters'
description: 'Install base dependencies and execute the linters'
inputs:
  repository_name:
    description: 'Repository name'
    required: true
runs:
  using: "composite"
  steps:
      - run: cp .flake8 .pylintrc .pre-commit-config.yaml ${{ inputs.repository_name }}
        shell: bash
      - working-directory: ${{ inputs.repository_name }}
        run: poetry run black --check .
        shell: bash
      - working-directory: ${{ inputs.repository_name }}
        run: poetry run flake8 --config=.flake8 .
        shell: bash
      - working-directory: ${{ inputs.repository_name }}
        run: poetry run pylint --rcfile=.pylintrc -j 0 --reports=n --recursive=true .
        shell: bash
      - working-directory: ${{ inputs.repository_name }}
        run: poetry run isort --check-only --profile=black .
        shell: bash
      - working-directory: ${{ inputs.repository_name }}
        run: poetry run toml-sort --in-place -a pyproject.toml
        shell: bash
