import os

# GOOGLE_APPLICATION_CREDENTIALS may not exist because authentication
# may be different from a Google product
GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
PROJECT_ID = os.environ["PROJECT_ID"]
REGION = os.environ["REGION"]
IMAGE_NAME = os.environ["IMAGE_NAME"]

OBJECT_DETECTION_MODEL_NAME = os.environ["OBJECT_DETECTION_MODEL_NAME"]
MODEL_INSTANTIATOR_HOST = os.environ["MODEL_INSTANTIATOR_HOST"]
FIRESTORE_RESULTS_COLLECTION = os.environ["FIRESTORE_RESULTS_COLLECTION"]
VIDEOS_TO_COUNT_BUCKET = os.environ["VIDEOS_TO_COUNT_BUCKET"]
COUNTED_VIDEOS_BUCKET = os.environ["COUNTED_VIDEOS_BUCKET"]
