import os

# GOOGLE_APPLICATION_CREDENTIALS may not exist because authentication
# may be different from a Google product
GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
OBJECT_DETECTION_MODEL_NAME = os.environ["OBJECT_DETECTION_MODEL_NAME"]
OBJECT_DETECTION_VERTEX_AI_LOCATION = os.environ["OBJECT_DETECTION_VERTEX_AI_LOCATION"]
MODEL_INSTANTIATOR_HOST = os.environ["MODEL_INSTANTIATOR_HOST"]
