import os

FIRESTORE_JOBS_COLLECTION = os.environ["FIRESTORE_JOBS_COLLECTION"]
GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
JOB_PREFIX_NAME = os.environ["JOB_PREFIX_NAME"]
PROJECT_ID = os.environ["PROJECT_ID"]
REGION = os.environ["REGION"]
SERIALIZED_SERVICE_CLIENT_PARAMETERS = os.environ[
    "SERIALIZED_SERVICE_CLIENT_PARAMETERS"
]
SERVICE_NAME = os.environ["SERVICE_NAME"]
