import os

MODEL_INSTANTIATOR_HOST = os.environ["MODEL_INSTANTIATOR_HOST"]
MODEL_NAME = os.environ["MODEL_NAME"]
PROJECT_ID = os.environ["PROJECT_ID"]
REGION = os.environ["REGION"]

GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
