name: 'run_linters_tests'
description: 'Install dev dependencies, execute linters and tests'
inputs:
  image_name:
    description: 'Image name'
    required: true
runs:
  using: "composite"
  steps:
      - run: |
          CONTAINER_ID=$(docker run -dit --entrypoint /bin/bash ${{ inputs.image_name }})
          echo "CONTAINER_ID"="$CONTAINER_ID" >> $GITHUB_ENV
          echo "MONO_REPOSITORY_PATH"="/mono_repository" >> $GITHUB_ENV
        shell: bash
      - run: docker cp ./. $CONTAINER_ID:$MONO_REPOSITORY_PATH
        shell: bash
      - run: |
          docker exec \
            --workdir $MONO_REPOSITORY_PATH \
            $CONTAINER_ID \
            /bin/bash -c "
              # to handle detected dubious ownership git issue
              git config --global --add safe.directory $MONO_REPOSITORY_PATH \
              && source ./.github/functions/install_terraform.sh \
              && install_terraform \
              && cd $REPOSITORY_NAME \
              && poetry export --without-hashes --with dev -f requirements.txt --output requirements.txt \
              && pip install -r requirements.txt \
              && cd $MONO_REPOSITORY_PATH \
              && pre-commit install \
              && pre-commit run \
                --show-diff-on-failure \
                --files $REPOSITORY_NAME/**/* \
              && pytest -x -n auto $REPOSITORY_NAME/tests/unit_tests -vv
          "
        shell: bash
      - run: docker rm -f $CONTAINER_ID
        shell: bash
