name: 'set_variables'
description: 'Configure environment variables for a workflow'
inputs:
  repository_name:
    description: 'The name of the repository whose variables are loaded'
    required: true
  set_up_terraform_variables:
    description: 'Whether to also create corresponding terraform variables'
    required: false
    default: 'true'
  variable_prefix_to_filter_on:
    description: 'Prefix of variables to keep'
    required: false
    default: ''
  discard_shared_variables:
    description: 'Whether discard shared variables or not'
    required: false
    default: 'false'
outputs:
  created_env_file_path:
    description: 'The environment variables file to load'
    value: ${{ steps.set_created_env_file_path.outputs.value }}
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/set_up_python
    - id: set_created_env_file_path
      run: |
        # temporary file that will be generated
        PREPROCESSED_VARIABLES_PATH=$(mktemp)
        echo "PREPROCESSED_VARIABLES_PATH=$PREPROCESSED_VARIABLES_PATH" >> $GITHUB_ENV
        echo "value=$PREPROCESSED_VARIABLES_PATH" >> $GITHUB_OUTPUT
      shell: bash

    - run: echo "set_created_env_file_path ${{ steps.set_created_env_file_path.outputs.value }}"
      shell: bash
    - run: |
        python3 .github/actions/set_variables/create_env_file.py \
          --repository_name ${{ inputs.repository_name }} \
          --environment_variables_file_path $PREPROCESSED_VARIABLES_PATH \
          --add_terraform_variables ${{ inputs.set_up_terraform_variables }} \
          --variable_prefix_to_filter_on "${{ inputs.variable_prefix_to_filter_on }}" \
          --discard_shared_variables ${{ inputs.discard_shared_variables }}
      shell: bash
    - uses: actions/download-artifact@v3
      with:
        name: ${{ env.CALLER_WORKFLOW_ENV_FILE_ARTIFACT_NAME }}
        path: /tmp
      if: ${{ env.CALLER_WORKFLOW_ENV_FILE_ARTIFACT_NAME != '' }}
    - run: |
        caller_workflow_env_file_path=/tmp/${{ env.CALLER_WORKFLOW_ENV_FILE_ARTIFACT_NAME }}
        refactored_caller_workflow_env_file_path=${caller_workflow_env_file_path}_refactored
          python3 .github/actions/set_variables/refactor_caller_workflow_env_file.py \
            --repository_where_variables_are_defined ${{ inputs.repository_name }} \
            --caller_workflow_env_file_path $caller_workflow_env_file_path \
            --refactored_caller_workflow_env_file_path $refactored_caller_workflow_env_file_path
        cat $refactored_caller_workflow_env_file_path >> $PREPROCESSED_VARIABLES_PATH
      if: ${{ env.CALLER_WORKFLOW_ENV_FILE_ARTIFACT_NAME != '' }}
      shell: bash
    - uses: cardinalby/export-env-action@v2
      with:
        envFile: ${{ env.PREPROCESSED_VARIABLES_PATH }}
        expand: 'true'
