name: 'set_variables'
description: 'Configure environment variables for a workflow'
inputs:
  repository_names:
    description: 'Name of the repositories'
    required: false
    default: ''
  set_up_terraform_variables:
    description: 'Whether to also create corresponding terraform variables'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    #        echo "SHARED_STATIC_VARIABLES_PATH=.github/variables/static_variables.env" >> $GITHUB_ENV
    #        echo "REPOSITORY_STATIC_VARIABLES_PATH"="$([[ ! -z '${{ inputs.repository_name }}' ]] && echo '${{ inputs.repository_name }}/iac/static_variables.env' || echo '')" >> $GITHUB_ENV
    #        echo "SHARED_DYNAMIC_VARIABLES_PATH=.github/variables/dynamic_variables.env" >> $GITHUB_ENV
    #        echo "REPOSITORY_DYNAMIC_VARIABLES_PATH"="$([[ ! -z '${{ inputs.repository_name }}' ]] && echo '${{ inputs.repository_name }}/iac/dynamic_variables.env' || echo '')" >> $GITHUB_ENV
    - run: |
        # temporary file that will be generated
        echo "PREPROCESSED_VARIABLES_PATH=/tmp/variables.env" >> $GITHUB_ENV
      shell: bash

    - run: |
        SHARED_STATIC_VARIABLES_PATH=".github/variables/static_variables.env"
        SHARED_DYNAMIC_VARIABLES_PATH=".github/variables/dynamic_variables.env"
        
        for repository_name in ${{ inputs.repository_names }}; do
          echo "test${repository_name}test"
          REPOSITORY_STATIC_VARIABLES_PATH=${repository_name:+"${repository_name}/iac/static_variables.env"}
          REPOSITORY_DYNAMIC_VARIABLES_PATH=${repository_name:+"$repository_name/iac/dynamic_variables.env"}
          # PREPROCESSED_VARIABLES_PATH="/tmp/${repository_name}_variables.env"
          
          for variables_path in $SHARED_STATIC_VARIABLES_PATH $REPOSITORY_STATIC_VARIABLES_PATH $SHARED_DYNAMIC_VARIABLES_PATH $REPOSITORY_DYNAMIC_VARIABLES_PATH; do
            if [ ! -f $variables_path ]; then
              continue
            fi
            current_preprocessed_variables_path=$(mktemp)
            # remove comment lines
            grep -v '^#' $variables_path > $current_preprocessed_variables_path
    
            # remove empty lines
            sed -ir '/^\s*$/d' $current_preprocessed_variables_path
    
            # add terraform variables
            if [ ${{ inputs.set_up_terraform_variables }} == 'true' ]; then
              terraform_variables_path=$(mktemp)
              cp $current_preprocessed_variables_path $terraform_variables_path
              sed -ir 's/\(.*=\)/\L\1/' $terraform_variables_path
              sed -ir 's/^/TF_VAR_/' $terraform_variables_path
              cat $terraform_variables_path >> $current_preprocessed_variables_path
            fi
  
            cat $current_preprocessed_variables_path >> $PREPROCESSED_VARIABLES_PATH
          done
        done
      shell: bash

    - uses: cardinalby/export-env-action@v2
      with:
        envFile: ${{ env.PREPROCESSED_VARIABLES_PATH }}
        expand: 'true'
