name: 'set_variables'
description: 'Configure environment variables for a workflow'
inputs:
  set_up_terraform_variables:
    description: 'Whether to also create corresponding terraform variables'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/set_up_python
    - run: |
        # temporary file that will be generated
        echo "PREPROCESSED_VARIABLES_PATH=/tmp/variables.env" >> $GITHUB_ENV
      shell: bash
    - run: |
        python3 .github/actions/set_variables/create_env_file.py --repository_name ${{ env.REPOSITORY_NAME }} --environment_variables_file_path $PREPROCESSED_VARIABLES_PATH --add_terraform_variables ${{ inputs.set_up_terraform_variables }}
      shell: bash
    - uses: cardinalby/export-env-action@v2
      with:
        envFile: ${{ env.PREPROCESSED_VARIABLES_PATH }}
        expand: 'true'
