import os

MODEL_INSTANTIATOR_HOST = os.environ["MODEL_INSTANTIATOR_HOST"]
MODEL_NAME = os.environ["MODEL_NAME"]
PEOPLE_COUNTING_URL = os.environ["PEOPLE_COUNTING_URL"]
PROJECT_ID = os.environ["PROJECT_ID"]
SERVICE_EVALUATOR_HOST = os.environ["SERVICE_EVALUATOR_HOST"]

GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
