import os

JOB_ID = os.environ["JOB_ID"]
ASSET_ID = os.environ["ASSET_ID"]
VIDEO_STORAGE_PATH = os.environ["VIDEO_STORAGE_PATH"]
FIRESTORE_RESULTS_COLLECTION = os.environ["FIRESTORE_RESULTS_COLLECTION"]
COUNTED_VIDEO_STORAGE_PATH = os.environ["COUNTED_VIDEO_STORAGE_PATH"]
