name: My Action
description: 'A YAML mapping or dictionary of keyword arguments'
inputs:
  terraform_disable_bools:
    required: true
    description: 'A YAML mapping or dictionary of keyword arguments'
runs:
  using: "composite"
  steps:
    - run: |
        for terraform_disable_bool in "${{ inputs.terraform_disable_bools }}"
          do
              export ${terraform_disable_bool^^}=0
              echo "${terraform_disable_bool^^}=0" >> $GITHUB_ENV
        
              export TF_VAR_${terraform_disable_bool,,}=0
              echo "TF_VAR_${terraform_disable_bool,,}=0" >> $GITHUB_ENV
          done
      shell: bash
    - run: |
        gcloud projects create ${{ env.PROJECT_ID }} --organization ${{ env.ORGANIZATION_ID }}  || true
        gcloud config set project ${{ env.PROJECT_ID }}
      shell: bash