import os

GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
MODEL_NAME = os.environ.get("MODEL_NAME")
PROJECT_ID = os.environ.get("PROJECT_ID")
REGION = os.environ.get("REGION")
MODEL_INSTANTIATOR_HOST = os.environ.get("MODEL_INSTANTIATOR_HOST")
