name: 'run_terraform'
description: 'Create the base infrastructure components, initialize and apply terraform'
inputs:
  targets:
    description: 'Terraform targets to build'
    required: true
  workspace:
    description: 'Terraform workspace to use, can be either "base" or "$REPOSITORY_NAME"'
    required: true
  image_name:
    description: 'Docker image name built'
    required: false
    default: ""  # can only be empty for partial terraform runs, aka runs that don't use "image_name"
  vars:
    description: 'Variables usually named -var found in the terraform plan and terraform apply commands'
    required: false
    default: ""
outputs:
  base_project_builder_sa_key:
    description: 'base project builder service account key'
    value: ${{ steps.terraform_with_retry.outputs.base_project_builder_sa_key }}

runs:
  using: "composite"
  steps:

    - run: echo "TF_VAR_image_name"="${{ inputs.image_name }}" >> $GITHUB_ENV
      shell: bash

    - uses: ./.github/actions/set_up_terraform

    - run: |
        if [[ ${{ inputs.workspace }} != "base" && ${{ inputs.workspace }} != "$REPOSITORY_NAME" ]]; then
          echo "Incorrect workspace input: expected $REPOSITORY_NAME or base, got ${{ inputs.workspace }}"
          exit 1
        fi
      shell: bash

    - run: |
        gcloud projects create $PROJECT_ID --set-as-default --organization $ORGANIZATION_ID 2>/dev/null || true
        echo "Waiting for project creation..." && sleep 5
        gcloud beta billing projects link $PROJECT_ID --billing-account $BILLING_ACCOUNT
      shell: bash

    - run: |
        # create state bucket
        gsutil mb -p $PROJECT_ID -c STANDARD -l $REGION -b on gs://$STATE_BUCKET || true
      shell: bash

    - id: add_iam_with_retry
      uses: nick-fields/retry@v2.8.2
      with:
        timeout_seconds: 30
        max_attempts: 3
        command: |
          for default_projects_owner in ${DEFAULT_PROJECTS_OWNERS//,/ }; do
            gcloud projects add-iam-policy-binding $PROJECT_ID --member=user:$default_projects_owner --role=roles/owner
          done

    # issue multiline? https://github.com/nick-fields/retry/issues/53
    - id: terraform_with_retry
      uses: nick-fields/retry@v2.8.2
      with:
        timeout_seconds: 1200
        max_attempts: 5
        retry_wait_seconds: 120
        command: |
          cd ${{ env.REPOSITORY_NAME }}/iac
          
          # run terraform init and create the terraform state locally
          terraform init -input=false -backend-config="bucket=$STATE_BUCKET"
  
          terraform workspace select ${{ inputs.workspace }} || terraform workspace new ${{ inputs.workspace }}
  
          # import the project in the terraform state
          terraform import google_project.project $PROJECT_ID 2>/dev/null || true
          
          # set up terraform -var arguments
          terraform_vars=""
          # if inputs.vars is not empty
          if [ -n "${{ inputs.vars }}" ]; then
            for input_var in "${{ inputs.vars }}"; do
                terraform_vars="$terraform_vars -var $input_var"
            done
          fi
  
          # set up terraform -target arguments
          terraform_targets=""
          # if inputs.targets is not empty
          if [ -n "${{ inputs.targets }}" ]; then
            for input_target in "${{ inputs.targets }}"; do
                terraform_targets="$terraform_targets -target $input_target"
            done
          fi
  
          # run terraform plan
          bash -c "terraform plan $terraform_vars $terraform_targets -input=false -out=tfplan"
  
          # run terraform apply
          bash -c "terraform apply -input=false -auto-approve tfplan"
          terraform_exit_status=$?
          
          echo "terraform exit status: $terraform_exit_status"

          # add the project builder key as the output of the action
          if [ ${{ inputs.workspace }} = "base" ]; then
            # get the key and remove the double quotes that create problems 
            # when you want to activate the service account
            base_project_builder_sa_key=$(terraform output base_project_builder_sa_key | tr -d '"')
          else
            base_project_builder_sa_key=""
          fi
          echo "base_project_builder_sa_key=$base_project_builder_sa_key"
          echo "base_project_builder_sa_key=$base_project_builder_sa_key" >> $GITHUB_OUTPUT
          
          # force script to terminate on terraform exit code to account for bug 
          # where last command dictates error or not: https://github.com/nick-fields/retry/issues/53
          exit $terraform_exit_status

    - id: release_terraform_lock
      if: ${{ failure() && steps.terraform_with_retry.conclusion == 'failure' }}
      run: gcloud storage rm gs://$STATE_BUCKET/terraform/state/${{ inputs.workspace }}.tflock || true
      shell: bash
