name: 'set_variables_gcloud_auth'
description: 'Execute in order the step set_variables and then the step gcloud_auth'
inputs:
  branch_name:
    description: 'GitHub current branch name'
    required: false
    default: ''
  set_up_terraform_variables:
    description: 'Whether to also create corresponding terraform variables'
    required: false
    default: 'true'
  variable_prefix_to_filter_on:
    description: 'Prefix of variables to keep, for example if people-counting is built from functional-people-counting, we only keep the corresponding variables, prefixed PEOPLE_COUNTING'
    required: false
    default: ''
  discard_shared_variables:
    description: 'Whether discard shared variables or not'
    required: false
    default: 'false'
  keep_repository_variables:
    description: 'Whether discard shared variables or not'
    required: false
    default: 'true'
  credentials_json:
    description: 'Name of the repositories'
    required: false
  env_file_artifact_name:
    description: 'An environment variable file to load'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
      - uses: ./.github/actions/set_variables
        with:
          branch_name: ${{ inputs.branch_name }}
          set_up_terraform_variables: ${{ inputs.set_up_terraform_variables }}
          variable_prefix_to_filter_on: ${{ inputs.variable_prefix_to_filter_on }}
          discard_shared_variables: ${{ inputs.discard_shared_variables }}
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}
          keep_repository_variables: ${{ inputs.keep_repository_variables }}
      - uses: ./.github/actions/gcloud_auth
        with:
          credentials_json: ${{ inputs.credentials_json }}
