name: 'set_variables_gcloud_auth'
description: 'Execute in order the step set_variables and then the step gcloud_auth'
inputs:
  set_up_terraform_variables:
    description: 'Whether to also create corresponding terraform variables'
    required: false
    default: 'true'
  variable_prefix_to_filter_on:
    description: 'Prefix of variables to keep, for example if people-counting is built from people-counting-functional, we only keep the corresponding variables, prefixed PEOPLE_COUNTING'
    required: false
    default: ''
  discard_shared_variables:
    description: 'Whether discard shared variables or not'
    required: false
    default: 'false'
  credentials_json:
    description: 'Name of the repositories'
    required: false
runs:
  using: "composite"
  steps:
      - uses: ./.github/actions/set_variables
        with:
          set_up_terraform_variables: ${{ inputs.set_up_terraform_variables }}
          variable_prefix_to_filter_on: ${{ inputs.variable_prefix_to_filter_on }}
          discard_shared_variables: ${{ inputs.discard_shared_variables }}
      - uses: ./.github/actions/gcloud_auth
        with:
          credentials_json: ${{ inputs.credentials_json }}
