name: 'set_up_poetry'
description: 'Install poetry'
inputs:
  version:
    description: 'The version of poetry to install'
    required: false
    default: '1.3.1'
outputs:
  version:
    description: 'The version of poetry installed'
    value: ${{ steps.set_poetry_version.outputs.value }}
runs:
  using: "composite"
  steps:
      - run: pip install poetry==${{ inputs.version }}
        shell: bash
      - id: set_poetry_version
        run: echo "value=${{ inputs.version }}" >> $GITHUB_OUTPUT
        shell: bash
