name: 'run_pre-commit'
description: 'Install base dependencies and execute pre-commit'
inputs:
  repository_path:
    description: 'Path of the repository to run pre-commit on'
    required: true
runs:
  using: "composite"
  steps:
      - run: cp .flake8 .pylintrc .pre-commit-config.yaml ${{ inputs.repository_path }}
        shell: bash
      - working-directory: ${{ inputs.repository_path }}
        run: poetry check && poetry install --with test
        shell: bash
      - working-directory: ${{ inputs.repository_path }}
        run: poetry run black --check .
        shell: bash
      - working-directory: ${{ inputs.repository_path }}
        run: poetry run flake8 --config=.flake8 .
        shell: bash
      - working-directory: ${{ inputs.repository_path }}
        run: poetry run pylint --rcfile=.pylintrc -j 0 --reports=n --recursive=true .
        shell: bash
      - working-directory: ${{ inputs.repository_path }}
        run: poetry run isort --check-only --profile=black .
        shell: bash
      - working-directory: ${{ inputs.repository_path }}
        run: poetry run toml-sort --in-place -a pyproject.toml
        shell: bash
