general:
  verbosity: True
  enable_video_writing: False
  enable_video_showing: False

dataset:
  google_drive_url: "https://drive.google.com/uc?id=18W81EE8LtNlzXG2xrgl0Fh102vyouD47"

preprocessing:
  image_width: 400


postprocessing:
  class_name: "person"
  confidence_threshold: 0.15


paths:
  videos_directory: "data"
  outputs_directory: "outputs"
  labels: "${paths.videos_directory}/labels.csv"
  benchmark: "${paths.outputs_directory}/benchmark.csv"
  scores: "${paths.outputs_directory}/scores.csv"
  output_file_suffix: "_results.txt"
  output_video_suffix: "_results.avi"

algorithm:
  line_placement_ratio: 0.5
  inference_periodicity: 3
  centroid_tracker:
    max_disappeared: 5
    max_distance_height_ratio: 0.2

# todo: to be removed when we start connecting the predictions
# to the object detector service
model:
  model_type: "ultralytics/yolov5"
  model_name: "yolov5x6"
  confidence_threshold: 0.15
