project_id: '${oc.env:PROJECT_ID}'
region: '${oc.env:REGION}'
name: 'object-detection'

model:
  name: "object_detection"
  inner_model_type: "ultralytics/yolov5"
  inner_model_name: "yolov5x6"
  image_width: 400

training:
  container_uri: "${oc.env:TRAINING_IMAGE_NAME}"
  machine_type: "e2-standard-4"
  accelerator_type: "ACCELERATOR_TYPE_UNSPECIFIED"
  accelerator_count: 0
  replica_count: 1

serving_model_upload:
  container_uri: "${oc.env:SERVING_IMAGE_NAME}"
  predict_route: "/predictions/${model.name}"
  health_route: "/ping"
  ports: [7080]

bigquery:
  dataset: '${project_id}.${model.name}_training'

storage:
  models_bucket_name: '${name}-models'
