import os

MODEL_NAME = os.environ["MODEL_NAME"]
UNDEPLOY_PREVIOUS_MODEL = os.environ.get("UNDEPLOY_PREVIOUS_MODEL")
IS_LAST_MODEL_ALREADY_DEPLOYED_OK = os.environ.get("IS_LAST_MODEL_ALREADY_DEPLOYED_OK")

UNDEPLOY_PREVIOUS_MODEL = (
    bool(UNDEPLOY_PREVIOUS_MODEL) if UNDEPLOY_PREVIOUS_MODEL is not None else True
)
IS_LAST_MODEL_ALREADY_DEPLOYED_OK = (
    bool(IS_LAST_MODEL_ALREADY_DEPLOYED_OK)
    if IS_LAST_MODEL_ALREADY_DEPLOYED_OK is not None
    else True
)
