import os

GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
SERVICE_ACCOUNT_EMAIL = os.environ.get("SERVICE_ACCOUNT_EMAIL")
TRAINING_IMAGE_NAME = os.environ.get("TRAINING_IMAGE_NAME")
PROJECT_ID = os.environ.get("PROJECT_ID")
MODEL_INSTANTIATOR_HOST = os.environ["MODEL_INSTANTIATOR_HOST"]
