import os

GOOGLE_APPLICATION_CREDENTIALS = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
TRAINING_IMAGE_NAME = os.environ.get("TRAINING_IMAGE_NAME")
PROJECT_ID = os.environ.get("PROJECT_ID")
MODEL_INSTANTIATOR_HOST = os.environ["MODEL_INSTANTIATOR_HOST"]
