name: 'set_up_terraform'
description: 'Install utilities that terraform needs that we might not have in a given docker image'
runs:
  using: "composite"
  steps:
      - name: install terraform
        run: |
          source ./.github/functions/install_terraform.sh
          install_terraform
        shell: bash
