name: 'set_up_terraform'
description: 'Install utilities that terraform needs that we might not have in a given docker image'
runs:
  using: "composite"
  steps:
      - name: Install terraform setup utilities
        run: |
          apt-get -y install zip
        shell: bash
      - name: Install node for terraform
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false