name: 'build_push'
description: 'Build and push docker image'
inputs:
  repository_name:
    description: 'Repository name'
    required: true
  artifact_registry_path:
    description: 'Artifact registry path'
    required: true
  target:
    description: >
      Docker target in case of a multi-stage build
      (e.g.: "train")
  build_arguments:
    description: >
      Docker build arguments 
      (e.g.: "--build-arg MODEL_PATH=model.pt --build-arg ARTIFACTS_PATH=artifacts")
  shared_repository_name:
    description: 'Shared repository name'
    default: shared
outputs:
  image_name:
    description: 'Built and pushed image name'
    value: ${{ steps.output_step.outputs.image_name }}
runs:
  using: "composite"
  steps:
    - run: echo "IMAGE_NAME_SUFFIX"="$([[ ! -z '${{ inputs.target }}' ]] && echo '-${{ inputs.target }}' || echo '')" >> $GITHUB_ENV
      shell: bash
    - run: echo "IMAGE_NAME"="${{ inputs.artifact_registry_path }}/${{ inputs.repository_name }}$IMAGE_NAME_SUFFIX" >> $GITHUB_ENV
      shell: bash
    - run: echo "TARGET_ARGUMENTS"="$([[ ! -z '${{ inputs.target }}' ]] && echo '--target ${{ inputs.target }}' || echo '')" >> $GITHUB_ENV
      shell: bash
    - run: docker pull $IMAGE_NAME:latest || true
      shell: bash
    - run: touch ${{ inputs.repository_name }}/.dockerignore
      shell: bash
    - run: |
        for to_include_line in '**/*' '!${{ inputs.repository_name }}' '!${{ inputs.shared_repository_name }}'
        do
          grep -qxF "$to_include_line" ${{ inputs.repository_name }}/.dockerignore || \
          echo "$to_include_line" >> ${{ inputs.repository_name }}/.dockerignore
        done
      shell: bash
    - run: cp ${{ inputs.repository_name }}/Dockerfile ${{ inputs.repository_name }}/.dockerignore .
      shell: bash
    - run: docker build --cache-from $IMAGE_NAME:latest -t $IMAGE_NAME:$GITHUB_RUN_ID -t $IMAGE_NAME:latest $TARGET_ARGUMENTS ${{ inputs.build_arguments }} .
      shell: bash
    - name: Run linters and tests
      uses: ./.github/actions/run_linters_tests
      with:
        repository_name: ${{ inputs.repository_name }}
        image_name: $IMAGE_NAME:$GITHUB_RUN_ID
    - run: docker push $IMAGE_NAME:$GITHUB_RUN_ID && docker push $IMAGE_NAME:latest
      shell: bash
    - id: output_step
      run: echo "image_name=$IMAGE_NAME:$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
      shell: bash
