name: 'set_up_python'
inputs:
  already_exists_do_the_set_up:
    description: 'Terraform targets to build'
    required: false
    default: 'false'
description: 'Install latest python'
runs:
  using: "composite"
  steps:
      - name: Install the latest version of python
        run: |
          set_up_python() {
            apt update
            apt install python3
            alias python=python3
          }
          if ! type python &>/dev/null; then
              echo "Python is not installed, setting up Python"
              set_up_python
          elif ${{ inputs.already_exists_do_the_set_up }}; then
              echo "Python is already installed, setting up Python anyway"
              set_up_python
          else
              echo "Python is already installed, skipping setting up Python"
          fi
        shell: bash
