name: 'set_up_python'
description: 'Install latest python'
runs:
  using: "composite"
  steps:
      - name: Install the latest version of python
        run: |
          apt update
          apt install python3
          alias python=python3
        shell: bash
