name: 'service-evaluator'
package_name: 'service_evaluator'
project_id: '${oc.env:PROJECT_ID}'
region: '${oc.env:REGION}'

job:
  container_uri: '${oc.env:IMAGE_NAME}'
  machine_type: 'e2-highmem-2'

paths:
  datasets_directory_name: 'datasets'
  dataset_filename: 'dataset.csv'

bigquery:
  dataset:
    name: '${oc.env:JOB_PREFIX_NAME}_results'
    forbidden_characters: ['-']
    forbidden_characters_replacements: ['_']
