name: core

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/core.yaml
      - .github/actions/**
      - .pre-commit-config.yaml
      - shared/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/core.yaml
      - .github/actions/**
      - .pre-commit-config.yaml
      - shared/**
  workflow_dispatch:

env:
  REPOSITORY_NAME: shared
  PYTHONPATH: shared

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    container: python:3.8-buster
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables_gcloud_auth
        with:
          repository_name: ${{ env.REPOSITORY_NAME }}
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
      - run: apt update && apt install -y cmake ffmpeg git libsm6 libxext6
      - run: pip install --upgrade pip
      - run: pip install poetry==$POETRY_VERSION
      - run: |
          cd $REPOSITORY_NAME \
          && poetry check \
          && poetry export --without-hashes -E dev -f requirements.txt --output requirements.txt \
          && pip install -r requirements.txt \
          && cd ..
      - run: |
          git config --global --add safe.directory $(pwd) \
          && pre-commit install \
          && pre-commit run --show-diff-on-failure --files $REPOSITORY_NAME/**/*
      - run: pytest -x -n auto $REPOSITORY_NAME/tests/unit_tests -vv
