name: abstract_functional_online_prediction_model

on:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
        default: 'true'
      deploy:
        required: false
        type: string
        default: 'true'
      do_post_deployment:
        required: false
        type: string
        default: 'true'
      env_file_artifact_name:
        required: false
        type: string
        default: ''
      online_prediction_model_repository:
        required: true
        type: string

env:
  REPOSITORY_NAME: ${{ inputs.online_prediction_model_repository }}

jobs:
  set_up_non_functional_repository_name:
    runs-on: ubuntu-latest
    container: google/cloud-sdk
    outputs:
      value: ${{ steps.set_up_non_functional_repository_name.outputs.value }}
    steps:
      - id: set_up_non_functional_repository_name
        run: |
          value=${REPOSITORY_NAME%-functional}
          echo value=$value >> $GITHUB_OUTPUT
        shell: bash

  run_base_terraform:
    runs-on: ubuntu-latest
    if: ${{ inputs.deploy == 'true' || inputs.deploy == '' }}
    container: google/cloud-sdk
    outputs:
      base_project_builder_sa_key: ${{ steps.run_base_terraform.outputs.base_project_builder_sa_key }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables_gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}
      - id: run_base_terraform
        uses: ./.github/actions/run_base_terraform

  upload_variables_of_called_workflows:
    runs-on: ubuntu-latest
    container: google/cloud-sdk
    outputs:
      online_prediction_model_env_file_artifact_name: ${{ steps.upload_online_prediction_model_variables.outputs.env_file_artifact_name }}
      model_instantiator_env_file_artifact_name: ${{ steps.upload_model_instantiator_variables.outputs.env_file_artifact_name }}
    steps:
      - uses: actions/checkout@v3
      - name: upload_online_prediction_model_variables
        id: upload_online_prediction_model_variables
        uses: ./.github/actions/upload_variables
        with:
          variable_prefix_to_filter_on: ${{ env.REPOSITORY_VARIABLES_PREFIX }}
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}
      - name: upload_model_instantiator_variables
        id: upload_model_instantiator_variables
        uses: ./.github/actions/upload_variables
        with:
          variable_prefix_to_filter_on: MODEL_INSTANTIATOR
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}


  build_test_push_online_prediction_model:
    needs: [set_up_non_functional_repository_name, run_base_terraform, upload_variables_of_called_workflows]
    uses: ./.github/workflows/abstract_online_prediction_model.yaml
    with:
      build: true
      deploy: false
      do_post_deployment: false
      env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.online_prediction_model_env_file_artifact_name }}
      online_prediction_model_repository: ${{ needs.set_up_non_functional_repository_name.outputs.value }}
    secrets: inherit

  build_test_push_model_instantiator:
    needs: [run_base_terraform, upload_variables_of_called_workflows]
    uses: ./.github/workflows/model_instantiator.yaml
    with:
      build: true
      deploy: false
      do_post_deployment: false
      env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.model_instantiator_env_file_artifact_name }}
    secrets: inherit

  deploy_functional_online_prediction_model:
    needs:
     - build_test_push_online_prediction_model
     - build_test_push_model_instantiator
     - run_base_terraform
    outputs:
      model_instantiator_url: ${{ steps.get_model_instantiator_url.outputs.value }}
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables_gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}
      - id: run_functional_online_prediction_model_terraform
        uses: ./.github/actions/run_terraform
        with:
          targets: ${{ env.MAIN_TERRAFORM_RESOURCES }}
          workspace: ${{ env.REPOSITORY_NAME }}
        # favor environment variables that show up clearly in github logs over
        # var-like arguments to make it easier to reproduce errors locally
        env:
          TF_VAR_model_instantiator_image_name: ${{ needs.build_test_push_model_instantiator.outputs.gcp_image_name }}
      - id: get_model_instantiator_url
        uses: ./.github/actions/get_terraform_output
        with:
          workspace: ${{ env.REPOSITORY_NAME }}
          terraform_output_name: model_instantiator_url

  post_deploy_online_prediction_model:
    # the job in the needs section is necessary to recover its output
    needs:
      - run_base_terraform
      - deploy_functional_online_prediction_model
      - build_test_push_online_prediction_model
      - upload_variables_of_called_workflows
      - set_up_non_functional_repository_name
    uses: ./.github/workflows/abstract_online_prediction_model.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: true
      gcp_training_image_name: ${{ needs.build_test_push_online_prediction_model.outputs.gcp_training_image_name }}
      dockerhub_training_image_name: ${{ needs.build_test_push_online_prediction_model.outputs.dockerhub_training_image_name }}
      base_project_builder_sa_key: ${{ needs.run_base_terraform.outputs.base_project_builder_sa_key }}
      model_instantiator_url: ${{ needs.deploy_functional_online_prediction_model.outputs.model_instantiator_url }}
      env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.online_prediction_model_env_file_artifact_name }}
      online_prediction_model_repository: ${{ needs.set_up_non_functional_repository_name.outputs.value }}
    secrets: inherit

  post_deploy_model_instantiator:
    needs: [deploy_functional_online_prediction_model, upload_variables_of_called_workflows]
    uses: ./.github/workflows/model_instantiator.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: true
      env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.model_instantiator_env_file_artifact_name }}
    secrets: inherit

  run_integration_tests:
    runs-on: ubuntu-latest
    needs:
      - post_deploy_online_prediction_model
      - post_deploy_model_instantiator
      - deploy_functional_online_prediction_model
    # If the workflow isn't called, inputs are blank and job should run
    if: ${{ (inputs.do_post_deployment == 'true' || inputs.do_post_deployment == '') && !failure() }}
    container: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables_gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}
      - id: get_model_name
        run: |
          # name_of_model_name_variable equals "OBJECT_DETECTION_MODEL_NAME" for example
          name_of_model_name_variable=${{ env.REPOSITORY_VARIABLES_PREFIX }}MODEL_NAME
          echo value=$(eval echo "\$${name_of_model_name_variable}") >> $GITHUB_OUTPUT
        shell: bash
      - uses: ./.github/actions/run_linters_tests
        with:
          image_name: python:3.9.17-slim-buster
          run_integration_tests: true
          run_unit_tests: false
          environment_variables: -e MODEL_NAME=${{ steps.get_model_name.outputs.value }} -e PROJECT_ID=${{ env.PROJECT_ID }} -e REGION=${{ env.REGION }}
