name: functional_object_detection

on:
#  push:
#    branches:
#      - main
#      - develop
#    paths:
#      - .github/workflows/functional_object_detection.yaml
#      - .github/actions/**
#      - .github/variables/**
#      - .pre-commit-config.yaml
#      - shared/**
#      - object-detection/**
#      - model-instantiator/**
#  pull_request:
#    branches:
#      - main
#      - develop
#    paths:
#      - .github/workflows/functional_object_detection.yaml
#      - .github/actions/**
#      - .github/variables/**
#      - .pre-commit-config.yaml
#      - shared/**
#      - object-detection/**
#      - model-instantiator/**
  workflow_dispatch:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
        default: 'true'
      deploy:
        required: false
        type: string
        default: 'true'
      do_post_deployment:
        required: false
        type: string
        default: 'true'
      env_file_artifact_name:
        required: false
        type: string
        default: ''
env:
  REPOSITORY_NAME: functional-object-detection
  GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
  TESTING_BASE_IMAGE: python:3.9.17-slim-buster

jobs:
  upload_variables_of_called_workflows:
    runs-on: neuronest-runner-set
    container: google/cloud-sdk
    outputs:
      env_file_artifact_name: ${{ steps.upload_variables.outputs.env_file_artifact_name }}
    steps:
      - uses: actions/checkout@v3
      - name: upload_variables
        id: upload_variables
        uses: ./.github/actions/upload_variables
        with:
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}

  functional_object_detection:
    needs: upload_variables_of_called_workflows
    uses: ./.github/workflows/functional_abstract_online_prediction_model.yaml
    with:
      build: true
      deploy: true
      do_post_deployment: true
      online_prediction_model_repository: functional-object-detection
      env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.env_file_artifact_name }}
    secrets: inherit
