name: model_instantiator

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/model_instantiator.yaml
      - dockerfiles/model_instantiator.dockerfile
      - shared/**
      - model-instantiator/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/model_instantiator.yaml
      - dockerfiles/model_instantiator.dockerfile
      - shared/**
      - model-instantiator/**
  workflow_dispatch:

env:
  IMAGE_REPOSITORY: model-instantiator
  PACKAGE_NAME: model_instantiator
  DOCKERFILE_PATH: dockerfiles/model_instantiator.dockerfile

jobs:
  build:
    name: build
    runs-on: self-hosted
    container: google/cloud-sdk
    outputs:
      IMAGE_NAME: ${{ steps.output_step.outputs.IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        uses: ./.github/actions/set_variables
      - run: mkdir -p $SERVICE_ACCOUNT_DIRECTORY && echo ${{ secrets.MODEL_INSTANTIATOR_CI_SERVICE_ACCOUNT }} | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
      - run: gcloud auth configure-docker $REGION-docker.pkg.dev
      - run: echo "IMAGE_NAME"="$ARTIFACT_REGISTRY_PATH/$IMAGE_REPOSITORY" >> $GITHUB_ENV
      - run: docker pull $IMAGE_NAME:latest || true
      - run: docker build --cache-from $IMAGE_NAME:latest -t $IMAGE_NAME:$GITHUB_RUN_ID -t $IMAGE_NAME:latest -f $DOCKERFILE_PATH .
      - run: docker push $IMAGE_NAME --all-tags
      - id: output_step
        run: echo "IMAGE_NAME=$IMAGE_NAME:$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

  tests:
    name: tests
    needs:
      - build
    runs-on: self-hosted
    container:
      image: ${{needs.build.outputs.IMAGE_NAME}}
      credentials:
        username: _json_key_base64
        password: ${{ secrets.MODEL_INSTANTIATOR_CI_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v3
      - name: Run pre-commit
        uses: ./.github/actions/run_pre_commit
        with:
          repository_path: model-instantiator

  run:
    name: run
    needs:
      - build
      - tests
    runs-on: self-hosted
    container: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        uses: ./.github/actions/set_variables
      - run: mkdir -p $SERVICE_ACCOUNT_DIRECTORY && echo ${{ secrets.MODEL_INSTANTIATOR_CI_SERVICE_ACCOUNT }} | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
      - run: gcloud run deploy service-name --set-env-vars PROJECT_ID=${PROJECT_ID},REGION=${REGION} --port 80 --cpu "1.0" --memory "128Mi" --image ${{needs.build.outputs.IMAGE_NAME}} --project ${PROJECT_ID} --region ${REGION}
