name: model_instantiator

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/model_instantiator.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - model-instantiator/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/model_instantiator.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - model-instantiator/**
  workflow_dispatch:
  workflow_call:
    inputs:
      deploy:
        required: false
        type: string
        default: true
    outputs:
      gcp_image_name:
        description: "The gcp image name"
        value: ${{ jobs.build_test_push.outputs.gcp_image_name }}

env:
  REPOSITORY_NAME: model-instantiator

jobs:
  build_test_push:
    name: build_test_push
    runs-on: ubuntu-latest
    container: google/cloud-sdk
    outputs:
      gcp_image_name: ${{ steps.build_test_push_deploy.outputs.gcp_image_name }}
    steps:
      - uses: actions/checkout@v3

      - id: set_variables
        uses: ./.github/actions/set_variables
        with:
          repository_names: model-instantiator

      - id: gcloud_auth
        uses: ./.github/actions/gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}

      - id: build_test_push_deploy
        uses: ./.github/actions/build_test_push_deploy
        with:
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
