name: neuronest

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    name: tests
    runs-on: self-hosted
    container: python:3.8-buster
    steps:
      - uses: actions/checkout@v3
      - run: pip install --upgrade pip
      - run: pip install poetry==1.2.2
      - run: poetry check
      - run: poetry pre-commit install
      - run: poetry pre-commit install --hook-type commit-msg
      - run: poetry run pre-commit run --all
