name: object_detection

on:
#  push:
#    branches:
#      - main
#      - develop
#    paths:
#      - .github/workflows/object_detection.yaml
#      - .github/actions/**
#      - .github/variables/**
#      - .pre-commit-config.yaml
#      - shared/**
#      - object-detection/**
#  pull_request:
#    branches:
#      - main
#      - develop
#    paths:
#      - .github/workflows/object_detection.yaml
#      - .github/actions/**
#      - .github/variables/**
#      - .pre-commit-config.yaml
#      - shared/**
#      - object-detection/**
#  workflow_dispatch:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
        default: 'true'
      deploy:
        required: false
        type: string
        default: 'true'
      do_post_deployment:
        required: false
        type: string
        default: 'true'
      env_file_artifact_name:
        required: false
        type: string
        default: ''
      base_project_builder_sa_key:
        required: false
        type: string
        default: ""
      dockerhub_training_image_name:
        required: false
        type: string
        default: ""
      gcp_training_image_name:
        required: false
        type: string
        default: ""
    outputs:
      gcp_training_image_name:
        description: "The gcp training image name"
        value: ${{ jobs.object_detection.outputs.gcp_training_image_name }}
      dockerhub_training_image_name:
        description: "The dockerhub training image name"
        value: ${{ jobs.object_detection.outputs.dockerhub_training_image_name }}
      base_project_builder_sa_key:
        description: 'The base64 encoded key of the IAC service account of the shared repository'
        value: ${{ jobs.object_detection.outputs.base_project_builder_sa_key }}
env:
  REPOSITORY_NAME: object-detection

jobs:
  upload_variables_of_called_workflows:
    runs-on: ubuntu-latest
    container: google/cloud-sdk
    outputs:
      env_file_artifact_name: ${{ steps.upload_variables.outputs.env_file_artifact_name }}
    steps:
      - uses: actions/checkout@v3
      - name: upload_variables
        id: upload_variables
        uses: ./.github/actions/upload_variables
        with:
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}

  object_detection:
    needs: upload_variables_of_called_workflows
    uses: ./.github/workflows/abstract_online_prediction_model.yaml
    with:
      build: ${{ inputs.build }}
      deploy: ${{ inputs.deploy }}
      do_post_deployment: ${{ inputs.do_post_deployment }}
      base_project_builder_sa_key: ${{ inputs.base_project_builder_sa_key }}
      dockerhub_training_image_name: ${{ inputs.dockerhub_training_image_name }}
      gcp_training_image_name: ${{ inputs.gcp_training_image_name }}
      online_prediction_model_repository: object-detection
      env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.env_file_artifact_name }}
    secrets: inherit
