name: object_detection

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/**
      - core/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/**
      - core/**

env:
  IMAGE_REPOSITORY: object-detection
  DOCKERFILE_PATH: dockerfiles/object_detection.dockerfile

jobs:
  build:
    name: build
    runs-on: self-hosted
    container: docker
    env:
      TARGET: training
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        uses: ./.github/actions/set_variables
      - run: docker build --build-arg STAGE=$STAGE -t $ARTIFACT_REGISTRY_PATH/$IMAGE_REPOSITORY:$GITHUB_RUN_ID -t $ARTIFACT_REGISTRY_PATH/$IMAGE_REPOSITORY:latest -f $DOCKERFILE_PATH --target $TARGET .
      - run: docker push $ARTIFACT_REGISTRY_PATH/$IMAGE_REPOSITORY --all-tags
