name: people_counting

on:
  push:
    branches:
      - main
      - develop
    tags-ignore:
      - v2
      - v1.*
    paths:
      - .github/workflows/people_counting.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
  pull_request:
    branches:
      - main
      - develop
    tags-ignore:
      - v2
      - v1.*
    paths:
      - .github/workflows/people_counting.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
  workflow_dispatch:
  workflow_call:
    inputs:
      deploy:
        required: false
        type: string
        default: true
    outputs:
      gcp_image_name:
        description: "The gcp image name"
        value: ${{ jobs.build_test_push_deploy.outputs.gcp_image_name }}

env:
  REPOSITORY_NAME: people-counting

jobs:
  build_test_push:
    name: build_test_push
    runs-on: ubuntu-latest
    container: google/cloud-sdk
    outputs:
      gcp_image_name: ${{ steps.build_test_push.outputs.gcp_image_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables
      - uses: ./.github/actions/gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
      - id: build_test_push
        uses: ./.github/actions/build_test_push
        with:
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: ${{ inputs.deploy == 'true' }}
    container:
      image: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables
      - uses: ./.github/actions/gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
      - uses: ./.github/actions/run_terraform
        with:
          targets: ${{ env.MAIN_TERRAFORM_RESOURCES }}
          workspace: ${{ env.REPOSITORY_NAME }}
          image_name: ${{ needs.jobs.build_test_push.steps.build_test_push.outputs.gcp_image_name }}
