name: people_counting

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/people_counting.yaml
      - .github/actions/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/people_counting.yaml
      - .github/actions/variables/**
      - .github/actions/build_test_push/**
      - .github/actions/set_up_terraform/**
      - .github/actions/gcloud_auth/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
  workflow_dispatch:

jobs:
  build_test_deploy:
    name: build_test_deploy
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/set_variables
        with:
          repository_static_variables_file_path: people-counting/iac/static_variables.env
          repository_dynamic_variables_file_path: people-counting/iac/dynamic_variables.env
          set_up_terraform_variables: true

      - uses: ./.github/actions/gcloud_auth
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}

      - name: terraform_run on necessary resources for ci
        uses: ./.github/actions/terraform_run
        with:
          targets: ${{ env.PEOPLE_COUNTING_NEEDED_RESOURCES_FOR_CI }}
          google_github_actions_auth_credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
          repository_name: ${{ env.REPOSITORY_NAME }}
        env:
          TF_VAR_webapp_image: ""

      - id: build_test_push_webapp_image
        uses: ./.github/actions/build_test_push
        with:
          repository_name: ${{ env.REPOSITORY_NAME }}
          repository_region: ${{ env.REGION }}
          gcp_registry_name: ${{ env.GCP_REGISTRY_NAME }}
          docker_repository_name: ${{ env.DOCKER_REPOSITORY_NAME }}
          dockerhub_username: ${{ fromJSON(secrets.DOCKERHUB_LOGIN).username }}
          dockerhub_password: ${{ fromJSON(secrets.DOCKERHUB_LOGIN).password }}

      - uses: ./.github/actions/terraform_run
        with:
          google_github_actions_auth_credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
          repository_name: ${{ env.REPOSITORY_NAME }}
        env:
          TF_VAR_webapp_image: ${{ steps.build_test_push_webapp_image.outputs.gcp_image_name }}
