name: people_counting_functional

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/people_counting_functional.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
      - object-detection/**
      - model-instantiator/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/people_counting_functional.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
      - object-detection/**
      - model-instantiator/**
  workflow_dispatch:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
        default: true
      deploy:
        required: false
        type: string
        default: true
      do_post_deployment:
        required: false
        type: string
        default: true
      caller_workflow_env_file_artifact_name:
        required: false
        type: string
        default: ''
env:
  REPOSITORY_NAME: people-counting-functional
  CALLER_WORKFLOW_ENV_FILE_ARTIFACT_NAME: ${{ inputs.caller_workflow_env_file_artifact_name }}

jobs:
  run_base_terraform:
    runs-on: ubuntu-latest
    if: ${{ inputs.deploy == 'true' || inputs.deploy == '' }}
    container: google/cloud-sdk
    outputs:
      base_project_builder_sa_key: ${{ steps.run_base_terraform.outputs.base_project_builder_sa_key }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables_gcloud_auth
        with:
          repository_name: ${{ env.REPOSITORY_NAME }}
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
      - id: run_base_terraform
        uses: ./.github/actions/run_base_terraform

  upload_variables_of_called_workflows:
    runs-on: ubuntu-latest
    container: google/cloud-sdk
    outputs:
      people_counting_env_file_artifact_name: ${{ steps.upload_people_counting_variables.outputs.env_file_artifact_name }}
      object_detection_env_file_artifact_name: ${{ steps.upload_object_detection_variables.outputs.env_file_artifact_name }}
      model_instantiator_env_file_artifact_name: ${{ steps.upload_model_instantiator_variables.outputs.env_file_artifact_name }}
    - id: upload_people_counting_variables
      uses: ./.github/actions/upload_variables
        with:
          variable_prefix_to_filter_on: PEOPLE_COUNTING
    - id: upload_object_detection_variables
      uses: ./.github/actions/upload_variables
        with:
          variable_prefix_to_filter_on: OBJECT_DETECTION
    - id: upload_model_instantiator_variables
      uses: ./.github/actions/upload_variables
        with:
          variable_prefix_to_filter_on: MODEL_INSTANTIATOR

  build_test_push_people_counting:
    needs: [run_base_terraform, upload_variables_of_called_workflows]
    uses: ./.github/workflows/people_counting.yaml
    with:
      build: true
      deploy: false
      do_post_deployment: false
      caller_workflow_env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.people_counting_env_file_artifact_name }}
    secrets: inherit

  build_test_push_object_detection:
    needs: [run_base_terraform, upload_variables_of_called_workflows]
    uses: ./.github/workflows/object_detection.yaml
    with:
      build: true
      deploy: false
      do_post_deployment: false
      caller_workflow_env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.object_detection_env_file_artifact_name }}
    secrets: inherit

  build_test_push_model_instantiator:
    needs: [run_base_terraform, upload_variables_of_called_workflows]
    uses: ./.github/workflows/model_instantiator.yaml
    with:
      build: true
      deploy: false
      do_post_deployment: false
      caller_workflow_env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.model_instantiator_env_file_artifact_name }}
    secrets: inherit

  deploy_people_counting_functional:
    needs:
     - build_test_push_people_counting
     - build_test_push_object_detection
     - build_test_push_model_instantiator
     - run_base_terraform
    outputs:
      model_instantiator_url: ${{ steps.get_model_instantiator_url.outputs.value }}
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables_gcloud_auth
        with:
          repository_name: ${{ env.REPOSITORY_NAME }}
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
      - id: run_people_counting_functional_terraform
        uses: ./.github/actions/run_terraform
        with:
          targets: ${{ env.MAIN_TERRAFORM_RESOURCES }}
          workspace: ${{ env.REPOSITORY_NAME }}
        # favor environment variables that show up clearly in github logs over
        # var-like arguments to make it easier to reproduce errors locally
        env:
          TF_VAR_model_instantiator_image_name: ${{ needs.build_test_push_model_instantiator.outputs.gcp_image_name }}
          TF_VAR_people_counting_image_name: ${{ needs.build_test_push_people_counting.outputs.gcp_image_name }}
      - id: get_model_instantiator_url
        uses: ./.github/actions/get_terraform_output
        with:
          workspace: ${{ env.REPOSITORY_NAME }}
          terraform_output_name: model_instantiator_url

  post_deploy_people_counting:
    needs: [deploy_people_counting_functional, upload_variables_of_called_workflows]
    uses: ./.github/workflows/people_counting.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: true
      caller_workflow_env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.people_counting_env_file_artifact_name }}
    secrets: inherit

  post_deploy_object_detection:
    # the job in the needs section is necessary to recover its output
    needs:
      - run_base_terraform
      - deploy_people_counting_functional
      - build_test_push_object_detection
      - upload_variables_of_called_workflows
    uses: ./.github/workflows/object_detection.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: true
      gcp_training_image_name: ${{ needs.build_test_push_object_detection.outputs.gcp_training_image_name }}
      dockerhub_training_image_name: ${{ needs.build_test_push_object_detection.outputs.dockerhub_training_image_name }}
      base_project_builder_sa_key: ${{ needs.run_base_terraform.outputs.base_project_builder_sa_key }}
      model_instantiator_url: ${{ needs.deploy_people_counting_functional.outputs.model_instantiator_url }}
      caller_workflow_env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.object_detection_env_file_artifact_name }}
    secrets: inherit

  post_deploy_model_instantiator:
    needs: [deploy_people_counting_functional, upload_variables_of_called_workflows]
    uses: ./.github/workflows/model_instantiator.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: true
      caller_workflow_env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.model_instantiator_env_file_artifact_name }}
    secrets: inherit
