name: people_counting

on:
#  push:
#    branches:
#      - main
#      - develop
#    paths:
#      - .github/workflows/people_counting.yaml
#      - .github/actions/**
#      - .github/variables/**
#      - .pre-commit-config.yaml
#      - shared/**
#      - people-counting/**
#  pull_request:
#    branches:
#      - main
#      - develop
#    paths:
#      - .github/workflows/people_counting.yaml
#      - .github/actions/**
#      - .github/variables/**
#      - .pre-commit-config.yaml
#      - shared/**
#      - people-counting/**
  workflow_dispatch:
  workflow_call:
    inputs:
      build:
        required: false
        type: string
        default: 'true'
      deploy:
        required: false
        type: string
        default: 'true'
      do_post_deployment:
        required: false
        type: string
        default: 'true'
      env_file_artifact_name:
        required: false
        type: string
        default: ''
    outputs:
      gcp_image_name:
        description: "The gcp image name"
        value: ${{ jobs.build_test_push.outputs.gcp_image_name }}

env:
  REPOSITORY_NAME: people-counting
  GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  run_base_terraform:
    runs-on: neuronest-runner-set
    # If the workflow isn't called, inputs are blank and all jobs should run
    if: ${{ inputs.deploy == 'true' || inputs.deploy == '' }}
    container: google/cloud-sdk
    outputs:
      base_project_builder_sa_key: ${{ steps.run_base_terraform.outputs.base_project_builder_sa_key }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables_gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}
      - id: run_base_terraform
        uses: ./.github/actions/run_base_terraform

  build_test_push:
    name: build_test_push
    runs-on: neuronest-runner-set
    needs: run_base_terraform
    # If the workflow isn't called, inputs are blank and job should run
    if: ${{ (inputs.build == 'true' || inputs.build == '') && !failure() && !cancelled() }}
    outputs:
      gcp_image_name: ${{ steps.build_test_push.outputs.gcp_image_name }}
      dockerhub_image_name: ${{ steps.build_test_push.outputs.dockerhub_image_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables
        with:
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}
          as_root: true
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
      - uses: ./.github/actions/gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
      - id: build_test_push
        uses: ./.github/actions/build_test_push
        with:
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  deploy:
    name: deploy
    runs-on: neuronest-runner-set
    needs:
      - run_base_terraform
      - build_test_push
    # If the workflow isn't called, inputs are blank and job should run
    if: ${{ (inputs.deploy == 'true' || inputs.deploy == '') && !failure() && !cancelled() }}
    container:
      image: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables_gcloud_auth
        with:
          credentials_json: ${{ needs.run_base_terraform.outputs.base_project_builder_sa_key }}
          env_file_artifact_name: ${{ inputs.env_file_artifact_name }}
      - uses: ./.github/actions/run_terraform
        with:
          targets: ${{ env.MAIN_TERRAFORM_RESOURCES }}
          workspace: ${{ env.REPOSITORY_NAME }}
          image_name: ${{ needs.build_test_push.outputs.gcp_image_name }}
