name: people_counting

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/people_counting.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/people_counting.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
  workflow_dispatch:

jobs:
  build_test_deploy:
    name: build_test_deploy
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3

      - id: set_variables
        uses: ./.github/actions/set_variables
        with:
          repository_name: people-counting

      - name: Loop over actions
        run: |
          for i in 1 2 3
          do
            echo "Running action $i"
            # Replace org/repo/action with the name of your reusable action
            # Replace tag with the version of the action you want to use
            # Replace arg1, arg2, and arg3 with the arguments you want to pass to the action
            # You can use $i to pass different arguments for each iteration
            uses: ./.github/actions/set_variables
            with:
              arg1: value1
              arg2: value2
              arg3: value3
          done

      - id: gcloud_auth
        uses: ./.github/actions/gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}

      - id: build_test_push_deploy
        uses: ./.github/actions/build_test_push_deploy
        with:
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
