name: people_counting_functional

on:
  push:
    branches:
      - main
      - develop
    tags:
      - people-counting-functional*
    paths:
      - .github/workflows/people_counting_functional.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/people_counting_functional.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
  workflow_dispatch:

env:
  REPOSITORY_NAME: people-counting-functional

jobs:
  run_base_terraform:
    runs-on: ubuntu-latest
    container: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables
      - uses: ./.github/actions/gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
      - uses: ./.github/actions/run_terraform
        with:
          targets: ${{ env.BASE_TERRAFORM_RESOURCES }}
          workspace: base

  build_test_push_people_counting:
    needs: run_base_terraform
    uses: ./.github/workflows/people_counting.yaml
    with:
      build: true
      deploy: false
      do_post_deployment: false
    secrets: inherit

  build_test_push_object_detection:
    needs: run_base_terraform
    uses: ./.github/workflows/object_detection.yaml
    with:
      build: true
      deploy: false
      do_post_deployment: false
    secrets: inherit

  build_test_push_model_instantiator:
    needs: run_base_terraform
    uses: ./.github/workflows/model_instantiator.yaml
    with:
      build: true
      deploy: false
      do_post_deployment: false
    secrets: inherit

  post_deploy_people_counting_first:
    needs: deploy_people_counting_functional
    uses: ./.github/workflows/people_counting.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: false
    secrets: inherit

  post_deploy_object_detection_first:
    needs: deploy_people_counting_functional
    uses: ./.github/workflows/object_detection.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: false
      gcp_training_image_name: test
      dockerhub_training_image_name: test
      base_project_builder_sa_key: test
    secrets: inherit

  post_deploy_model_instantiator_first:
    needs: deploy_people_counting_functional
    uses: ./.github/workflows/model_instantiator.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: false
    secrets: inherit

  deploy_people_counting_functional:
    needs:
     - build_test_push_people_counting
     - build_test_push_object_detection
     - build_test_push_model_instantiator
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables
      - uses: ./.github/actions/gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
      - uses: ./.github/actions/run_terraform
        with:
          targets: ${{ env.MAIN_TERRAFORM_RESOURCES }}
          workspace: ${{ env.REPOSITORY_NAME }}
          vars: |-
            model_instantiator_image_name=${{ needs.build_test_push_model_instantiator.outputs.gcp_image_name }}
            people_counting_image_name=${{ needs.build_test_push_people_counting.outputs.gcp_image_name }}

  post_deploy_people_counting:
    needs: deploy_people_counting_functional
    uses: ./.github/workflows/people_counting.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: true
    secrets: inherit

  post_deploy_object_detection:
    needs: deploy_people_counting_functional
    uses: ./.github/workflows/object_detection.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: true
      gcp_training_image_name: ${{ needs.jobs.build_test_push_object_detection.outputs.gcp_training_image_name }}
      dockerhub_training_image_name: ${{ needs.jobs.build_test_push_object_detection.outputs.dockerhub_training_image_name }}
      base_project_builder_sa_key: ${{ needs.jobs.build_test_push_object_detection.outputs.base_project_builder_sa_key }}
    secrets: inherit

  post_deploy_model_instantiator:
    needs: deploy_people_counting_functional
    uses: ./.github/workflows/model_instantiator.yaml
    with:
      build: false
      deploy: false
      do_post_deployment: true
    secrets: inherit