name: people_counting

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/people_counting.yaml
      - .github/actions/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/people_counting.yaml
      - .github/actions/variables/**
      - .github/actions/build_test_push/**
      - .github/actions/set_up_terraform/**
      - .github/actions/gcloud_auth/**
      - .pre-commit-config.yaml
      - shared/**
      - people-counting/**
  workflow_dispatch:

jobs:
  build_test_deploy:
    name: build_test_deploy
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
      - uses: actions/checkout@v3

      - id: set_variables
        uses: ./.github/actions/set_variables
        with:
          repository_static_variables_file_path: people-counting/iac/static_variables.env
          repository_dynamic_variables_file_path: people-counting/iac/dynamic_variables.env
          set_up_terraform_variables: true

      - id: gcloud_auth
        uses: ./.github/actions/gcloud_auth
        with:
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}

      - id: prior_run_terraform
        uses: ./.github/actions/run_terraform
        with:
          targets: ${{ env.PRIOR_TERRAFORM_RESOURCES }}
          image_name: ""  # set emtpy for a partial terraform run

      - id: build_test_push
        uses: ./.github/actions/build_test_push
        with:
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - id: run_terraform
        uses: ./.github/actions/run_terraform
        with:
          image_name: ${{ steps.build_test_push.outputs.gcp_image_name }}
