name: run_base_terraform

on:
  workflow_call:
    inputs:
      repository_name:
        description: 'Whether to also create corresponding terraform variables'
        required: true
        default: 'true'
    outputs:
      base_project_builder_sa_key:
        description: "The gcp image name"
        value: ${{ jobs.run_base_terraform.outputs.base_project_builder_sa_key }}

jobs:
  run_base_terraform:
    runs-on: ubuntu-latest
    container: google/cloud-sdk
    outputs:
      base_project_builder_sa_key: ${{ steps.run_base_terraform.outputs.base_project_builder_sa_key }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/set_variables_gcloud_auth
        with:
          repository_name: ${{ inputs.repository_name }}
          credentials_json: ${{ secrets.NEURONEST_INFRASTRUCTURE_BUILDER_SERVICE_ACCOUNT }}
      - id: run_base_terraform
        uses: ./.github/actions/run_base_terraform
