name: customer_dummy_project

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/video_comparator_dummy_project.yaml
      - .github/workflows/abstract_online_prediction_model_functional.yaml
      - .github/workflows/abstract_online_prediction_model.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - model-instantiator/**
      - video-comparator/**
      - object-detection/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/video_comparator_dummy_project.yaml
      - .github/actions/**
      - .github/variables/**
      - .pre-commit-config.yaml
      - shared/**
      - model-instantiator/**
      - video-comparator/**
      - object-detection/**
  workflow_dispatch:

env:
  REPOSITORY_NAME: customer-dummy-project

jobs:
  upload_variables_of_called_workflows:
    runs-on: ubuntu-latest
    container: google/cloud-sdk
    outputs:
      env_file_artifact_name: ${{ steps.upload_variables.outputs.env_file_artifact_name }}
    steps:
      - uses: actions/checkout@v3
      - name: upload_variables
        id: upload_variables
        uses: ./.github/actions/upload_variables

  object_detection_functional:
    needs: upload_variables_of_called_workflows
    uses: ./.github/workflows/object_detection_functional.yaml
    with:
      build: true
      deploy: true
      do_post_deployment: true
      env_file_artifact_name: ${{ needs.upload_variables_of_called_workflows.outputs.env_file_artifact_name }}
    secrets: inherit
